#!/usr/bin/env bash
# Install the DynaBARN dynamic-obstacle worlds into the BARN ROS2 evaluator and
# wire the evaluator launch so gz-sim can find the DynamicObstacle mover plugin
# (otherwise the cylinders stay frozen at their spawn pose and never move).
set -euo pipefail

# Resolve the repo root from this script's location (tools/ lives at repo root).
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." >/dev/null 2>&1 && pwd)"

SRC_DIR="${REPO_ROOT}/worlds/DynaBARN"
EVAL_DIR="${REPO_ROOT}/ros2_ws/src/The-Barn-Challenge-Ros2"
DST_DIR="${EVAL_DIR}/jackal_helper/worlds/DynaBARN"
LAUNCH_FILE="${EVAL_DIR}/jackal_helper/launch/BARN_runner.launch.py"
PLUGIN_DIR="${REPO_ROOT}/simulation/barn_dynamic_obstacle/build"
PLUGIN_SO="${PLUGIN_DIR}/libbarn_dynamic_obstacle.so"

if [ ! -d "${SRC_DIR}" ]; then
  echo "ERROR: source worlds dir not found: ${SRC_DIR}" >&2
  exit 1
fi

# --- 1. Copy the world files into the evaluator ------------------------------
shopt -s nullglob
worlds=("${SRC_DIR}"/*.world)
if [ ${#worlds[@]} -eq 0 ]; then
  echo "ERROR: no *.world files in ${SRC_DIR}" >&2
  exit 1
fi
mkdir -p "${DST_DIR}"
for w in "${worlds[@]}"; do
  cp -v "${w}" "${DST_DIR}/"
done

# --- 2. Check the mover plugin is built --------------------------------------
if [ ! -f "${PLUGIN_SO}" ]; then
  echo
  echo "WARNING: mover plugin not built: ${PLUGIN_SO}" >&2
  echo "Build it (inside the ROS 2 Jazzy distrobox) with:" >&2
  echo "  source /opt/ros/jazzy/setup.bash" >&2
  echo "  cmake -S ${REPO_ROOT}/simulation/barn_dynamic_obstacle -B ${PLUGIN_DIR} && cmake --build ${PLUGIN_DIR} -j" >&2
  echo "Without it the DynaBARN cylinders will not move." >&2
fi

# --- 3. Make the plugin discoverable by the evaluator's gz server -------------
# Inject a SetEnvironmentVariable for GZ_SIM_SYSTEM_PLUGIN_PATH into the launch,
# idempotently (skips if already present). The clone is git-ignored and gets
# regenerated by setup_barn_eval.sh, so this script owns the wiring.
if [ -f "${LAUNCH_FILE}" ]; then
  python3 - "${LAUNCH_FILE}" "${PLUGIN_DIR}" <<'PYEOF'
import sys

path = sys.argv[1]
plugin_dir = sys.argv[2]
with open(path, "r", encoding="utf-8") as f:
    text = f.read()

if "set_dyn_plugin_path" in text:
    print(f"[setup_dynabarn] plugin path already wired in {path}")
    sys.exit(0)

def_anchor = ('    set_logging_format = SetEnvironmentVariable('
              'name="RCUTILS_CONSOLE_OUTPUT_FORMAT", '
              'value="[{severity}] [{name}]: {message}")')
inject_def = def_anchor + f"""

    # Make the DynaBARN moving-obstacle plugin (barn_dynamic_obstacle) discoverable
    # by the gz server so cylinders in DynaBARN worlds actually move. Absolute path
    # (this launch runs from the colcon install tree, not the repo source, so a
    # __file__-relative walk resolves against ros2_ws/install and fails).
    set_dyn_plugin_path = SetEnvironmentVariable(
        name='GZ_SIM_SYSTEM_PLUGIN_PATH',
        value=os.pathsep.join(
            p for p in ('{plugin_dir}', os.environ.get('GZ_SIM_SYSTEM_PLUGIN_PATH', '')) if p))"""

add_anchor = "    ld.add_action(set_logging_format)"
inject_add = add_anchor + "\n    ld.add_action(set_dyn_plugin_path)"

if def_anchor not in text or add_anchor not in text:
    print(f"[setup_dynabarn] WARNING: could not find injection anchors in {path}; "
          "set GZ_SIM_SYSTEM_PLUGIN_PATH manually.", file=sys.stderr)
    sys.exit(0)

text = text.replace(def_anchor, inject_def, 1).replace(add_anchor, inject_add, 1)
if "import os" not in text:
    text = "import os\n" + text
with open(path, "w", encoding="utf-8") as f:
    f.write(text)
print(f"[setup_dynabarn] wired GZ_SIM_SYSTEM_PLUGIN_PATH into {path}")
PYEOF
else
  echo "WARNING: evaluator launch not found: ${LAUNCH_FILE}" >&2
  echo "Run tools/setup_barn_eval.sh first." >&2
fi

echo
echo "Installed ${#worlds[@]} world(s) into: ${DST_DIR}"
echo "world_idx 300/301/302 -> DynaBARN world_0/1/2 (easy/medium/hard)."
echo
echo "Run the DYNAMIC stack (tracker + moving-obstacle MPC) on a DynaBARN world:"
echo "  ros2 launch jackal_helper BARN_runner.launch.py algo_type:=classical_mpc_dynamic world_idx:=300 gui:=true planner_rviz:=true"
echo
echo "If gz was launched from a shell without this wiring, export manually:"
echo "  export GZ_SIM_SYSTEM_PLUGIN_PATH=${PLUGIN_DIR}"
echo
